// EduSusten - Base de Dados e Configurações Reais do Google Apps Script
export const GAS_CONFIG = {
  deploymentCode: 'AKfycbxZ_p3v2wcpM2m9n55rquwfY1PDpAde-98J_ua-K09fNHioEbFEtnhqxdKQpFbAOcewTA',
  webAppUrl: 'https://script.google.com/macros/s/AKfycbxZ_p3v2wcpM2m9n55rquwfY1PDpAde-98J_ua-K09fNHioEbFEtnhqxdKQpFbAOcewTA/exec',
  proxyUrl: '/api/ranking'
};

// Indicadores com as pontuações e pesos exatos da planilha real (Total: 1.000 pts)
export const CATEGORIAS_INFO = [
  {
    id: 'energia',
    nome: 'Energia',
    chaveGas: 'Energia (Máx 300)',
    icone: 'zap',
    cor: '#cca549',
    peso: '30%',
    pontosMax: 300,
    descricao: 'Eficiência energética, uso de luz natural, fontes renováveis (solar) e conscientização do consumo.',
    criterios: [
      'Geração e uso de energia solar fotovoltaica',
      'Eficiência energética e iluminação 100% LED',
      'Aproveitamento máximo da iluminação natural',
      'Campanhas contínuas de desligamento e monitoramento'
    ]
  },
  {
    id: 'agua',
    nome: 'Água',
    chaveGas: 'Água (Máx 200)',
    icone: 'droplets',
    cor: '#2f4a69',
    peso: '20%',
    pontosMax: 200,
    descricao: 'Captação de água da chuva, torneiras automáticas/econômicas e reúso.',
    criterios: [
      'Captação e cisternas de água pluvial para limpeza e rega',
      'Torneiras com temporizador e redutores de vazão',
      'Sistemas de reúso de águas cinzas',
      'Combate a vazamentos e hidrômetros setorizados'
    ]
  },
  {
    id: 'infraestrutura',
    nome: 'Infraestrutura',
    chaveGas: 'Infraestrutura (Máx 150)',
    icone: 'building-2',
    cor: '#177147',
    peso: '15%',
    pontosMax: 150,
    descricao: 'Áreas verdes, arborização, horta escolar, permeabilidade do solo e ventilação.',
    criterios: [
      'Áreas permeáveis e cobertura vegetal nativa',
      'Horta escolar ativa integrada às refeições e aulas',
      'Conforto bioclimático e ventilação cruzada nas salas',
      'Acessibilidade ecológica e calçadas drenantes'
    ]
  },
  {
    id: 'residuos',
    nome: 'Resíduos',
    chaveGas: 'Resíduos (Máx 150)',
    icone: 'recycle',
    cor: '#118552',
    peso: '15%',
    pontosMax: 150,
    descricao: 'Coleta seletiva, compostagem de resíduos orgânicos e redução de plástico de uso único.',
    criterios: [
      'Coleta seletiva em todas as salas e áreas comuns',
      'Compostagem de resíduos orgânicos da merenda',
      'Eliminação de copos e descartáveis plásticos de uso único',
      'Descarte ambientalmente correto de pilhas e eletrônicos'
    ]
  },
  {
    id: 'educacao',
    nome: 'Educação Ambiental',
    chaveGas: 'Educação Ambiental (Máx 200)',
    icone: 'sprout',
    cor: '#22a267',
    peso: '20%',
    pontosMax: 200,
    descricao: 'Projetos pedagógicos transversais, feiras de ciências ecológicas e envolvimento da comunidade.',
    criterios: [
      'Projetos interdisciplinares com foco em ODS da ONU',
      'Feira anual de sustentabilidade e ciências',
      'Comitê escolar mirim de meio ambiente',
      'Ações ecológicas integradas à comunidade do bairro'
    ]
  }
];

// Dados reais espelhados diretamente da planilha do Google Apps Script
export const ESCOLAS_FUNDAMENTAL_INICIAIS = [
  {
    id: 'ef-01',
    posicao: 1,
    nome: 'Escola Exemplo A',
    localizacao: 'Cabo de Santo Agostinho - PE',
    cidade: 'Cabo de Santo Agostinho',
    uf: 'PE',
    nivel: 'Ouro',
    pontuacaoTotal: 920,
    pontuacaoMax: 1000,
    energia: 280,
    agua: 190,
    infraestrutura: 140,
    residuos: 130,
    educacao: 180,
    observacoes: 'Excelente em energia solar',
    destaque: 'Excelente em energia solar e captação pluvial avançada.',
    anoAvaliaca: 2026,
    selo: 'Selo Ouro',
    alunos: 620,
    residuosRecicladosTon: 14.2
  },
  {
    id: 'ef-02',
    posicao: 2,
    nome: 'Escola Exemplo B',
    localizacao: 'Cabo de Santo Agostinho - PE',
    cidade: 'Cabo de Santo Agostinho',
    uf: 'PE',
    nivel: 'Bronze',
    pontuacaoTotal: 540,
    pontuacaoMax: 1000,
    energia: 150,
    agua: 100,
    infraestrutura: 80,
    residuos: 90,
    educacao: 120,
    observacoes: 'Precisa de melhorias na coleta seletiva',
    destaque: 'Plano de ação em andamento para melhorias na coleta seletiva e compostagem.',
    anoAvaliaca: 2026,
    selo: 'Escola Compromissada',
    alunos: 480,
    residuosRecicladosTon: 5.6
  },
  {
    id: 'ef-03',
    posicao: 3,
    nome: 'Escola Exemplo C',
    localizacao: 'Cabo de Santo Agostinho - PE',
    cidade: 'Cabo de Santo Agostinho',
    uf: 'PE',
    nivel: 'Participante',
    pontuacaoTotal: 0,
    pontuacaoMax: 1000,
    energia: 0,
    agua: 0,
    infraestrutura: 0,
    residuos: 0,
    educacao: 0,
    observacoes: 'Em fase de envio de evidências',
    destaque: 'Inscrita na plataforma. Aguardando auditoria do ciclo 2026.',
    anoAvaliaca: 2026,
    selo: 'Em Avaliação',
    alunos: 350,
    residuosRecicladosTon: 0
  },
  {
    id: 'ef-04',
    posicao: 4,
    nome: 'Escola Exemplo D',
    localizacao: 'Cabo de Santo Agostinho - PE',
    cidade: 'Cabo de Santo Agostinho',
    uf: 'PE',
    nivel: 'Participante',
    pontuacaoTotal: 0,
    pontuacaoMax: 1000,
    energia: 0,
    agua: 0,
    infraestrutura: 0,
    residuos: 0,
    educacao: 0,
    observacoes: 'Em fase de envio de evidências',
    destaque: 'Inscrita na plataforma. Aguardando auditoria do ciclo 2026.',
    anoAvaliaca: 2026,
    selo: 'Em Avaliação',
    alunos: 410,
    residuosRecicladosTon: 0
  },
  {
    id: 'ef-05',
    posicao: 5,
    nome: 'Escola Exemplo E',
    localizacao: 'Cabo de Santo Agostinho - PE',
    cidade: 'Cabo de Santo Agostinho',
    uf: 'PE',
    nivel: 'Participante',
    pontuacaoTotal: 0,
    pontuacaoMax: 1000,
    energia: 0,
    agua: 0,
    infraestrutura: 0,
    residuos: 0,
    educacao: 0,
    observacoes: 'Em fase de envio de evidências',
    destaque: 'Inscrita na plataforma. Aguardando auditoria do ciclo 2026.',
    anoAvaliaca: 2026,
    selo: 'Em Avaliação',
    alunos: 390,
    residuosRecicladosTon: 0
  }
];

export const ESCOLAS_MEDIO_INICIAIS = [
  {
    id: 'em-01',
    posicao: 1,
    nome: 'Escola Exemplo A',
    localizacao: 'Cabo de Santo Agostinho - PE',
    cidade: 'Cabo de Santo Agostinho',
    uf: 'PE',
    nivel: 'Ouro',
    pontuacaoTotal: 920,
    pontuacaoMax: 1000,
    energia: 280,
    agua: 190,
    infraestrutura: 140,
    residuos: 130,
    educacao: 180,
    observacoes: 'Excelente em energia solar',
    destaque: 'Excelente em energia solar com placas fotovoltaicas e laboratório verde.',
    anoAvaliaca: 2026,
    selo: 'Selo Ouro',
    alunos: 850,
    residuosRecicladosTon: 22.4
  },
  {
    id: 'em-02',
    posicao: 2,
    nome: 'Escola Exemplo B',
    localizacao: 'Cabo de Santo Agostinho - PE',
    cidade: 'Cabo de Santo Agostinho',
    uf: 'PE',
    nivel: 'Bronze',
    pontuacaoTotal: 540,
    pontuacaoMax: 1000,
    energia: 150,
    agua: 100,
    infraestrutura: 80,
    residuos: 90,
    educacao: 120,
    observacoes: 'Precisa de melhorias na coleta seletiva',
    destaque: 'Desenvolvendo cooperativa estudantil para melhorias na coleta seletiva.',
    anoAvaliaca: 2026,
    selo: 'Escola Compromissada',
    alunos: 720,
    residuosRecicladosTon: 8.9
  },
  {
    id: 'em-03',
    posicao: 3,
    nome: 'Escola Exemplo C',
    localizacao: 'Cabo de Santo Agostinho - PE',
    cidade: 'Cabo de Santo Agostinho',
    uf: 'PE',
    nivel: 'Participante',
    pontuacaoTotal: 0,
    pontuacaoMax: 1000,
    energia: 0,
    agua: 0,
    infraestrutura: 0,
    residuos: 0,
    educacao: 0,
    observacoes: 'Em fase de envio de evidências',
    destaque: 'Cadastro inicial confirmado no Ensino Médio.',
    anoAvaliaca: 2026,
    selo: 'Em Avaliação',
    alunos: 590,
    residuosRecicladosTon: 0
  },
  {
    id: 'em-04',
    posicao: 4,
    nome: 'Escola Exemplo D',
    localizacao: 'Cabo de Santo Agostinho - PE',
    cidade: 'Cabo de Santo Agostinho',
    uf: 'PE',
    nivel: 'Participante',
    pontuacaoTotal: 0,
    pontuacaoMax: 1000,
    energia: 0,
    agua: 0,
    infraestrutura: 0,
    residuos: 0,
    educacao: 0,
    observacoes: 'Em fase de envio de evidências',
    destaque: 'Cadastro inicial confirmado no Ensino Médio.',
    anoAvaliaca: 2026,
    selo: 'Em Avaliação',
    alunos: 640,
    residuosRecicladosTon: 0
  },
  {
    id: 'em-05',
    posicao: 5,
    nome: 'Escola Exemplo E',
    localizacao: 'Cabo de Santo Agostinho - PE',
    cidade: 'Cabo de Santo Agostinho',
    uf: 'PE',
    nivel: 'Participante',
    pontuacaoTotal: 0,
    pontuacaoMax: 1000,
    energia: 0,
    agua: 0,
    infraestrutura: 0,
    residuos: 0,
    educacao: 0,
    observacoes: 'Em fase de envio de evidências',
    destaque: 'Cadastro inicial confirmado no Ensino Médio.',
    anoAvaliaca: 2026,
    selo: 'Em Avaliação',
    alunos: 520,
    residuosRecicladosTon: 0
  }
];
